import { type ReactNode, useState } from 'react';
import { Link } from '@tanstack/react-router';
import { ArrowRight, ChevronRight, Phone, Mail, MapPin, MessageCircle } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { business, categories, distribution, services } from '@/data/site';
import { ProductGrid, VisionMission, TrustedBrands, DistributionLists, ServiceList, WhyChoose } from './sections';
import construction from '@/assets/construction.webp';
import { enquiryLink, trackEvent } from '@/lib/analytics';

export function PageFrame({ title, description, children, products = false }: { title: string; description: string; children: ReactNode; products?: boolean }) { return <div className="site-width inner-page"><nav className="breadcrumbs" aria-label="Breadcrumb"><Link to="/">Home</Link><ChevronRight />{products && <><Link to="/products">Products</Link><ChevronRight /></>}<span aria-current="page">{title}</span></nav><h1 className="page-heading">{title}</h1><p className="page-lead">{description}</p>{children}</div> }
export function ProductsPage() { return <PageFrame title="Our Products" description="Hardware, building materials and home solutions — for your next project, from foundation to finish."><ProductGrid /><div className="mt-10"><Button variant="gold" asChild><Link to="/contact">Enquire About Products <ArrowRight /></Link></Button></div></PageFrame> }
export function CategoryPage({ slug }: { slug: string }) { const category = categories.find(c => c.slug === slug); if (!category) return null; return <PageFrame products title={category.name} description={`${category.description} Available through Keerthi Agencies in Athikkayam, Pathanamthitta.`}><div className="category-detail"><img src={category.image} width={320} height={320} alt={category.name} /><div><h2>Find the right materials for your project</h2><p>Whether you are purchasing for your home, a construction site or your business, speak to our team about your requirements. Ask us about brands, specifications, quantities and current availability before placing an order.</p><div className="flex flex-wrap gap-3"><Button asChild variant="gold"><Link to="/contact">Enquire Now <ArrowRight /></Link></Button><Button asChild variant="goldOutline"><a href={business.phoneLinks[0]} onClick={() => trackEvent('phone_click')}><Phone />Call Our Team</a></Button></div></div></div><h2 className="section-title mt-10">More Products</h2><ProductGrid /></PageFrame> }
export function AboutPage() { return <PageFrame title="About Keerthi" description="Building Trust. Creating Value. Your building materials and hardware partner in Athikkayam, Pathanamthitta."><div className="about-page-grid"><div><h2 className="section-title">Keerthi Group of Companies</h2><p>Keerthi Agencies brings together hardware, building materials, construction products, plumbing, electrical and home solutions. Our business combines retail, wholesale and hardware distribution to serve homeowners, retailers, contractors and builders.</p><p>From everyday repairs to construction requirements, our focus is on quality products, trusted brands and dependable service. Visit us opposite Athikkayam Bus Stand, near SBI Bank, to discuss your next project.</p><VisionMission /><div className="mt-7"><Button asChild variant="gold"><Link to="/contact">Contact Us <ArrowRight /></Link></Button></div></div><img src={construction} width={768} height={1024} loading="lazy" alt="Construction materials and safety helmet" /></div></PageFrame> }
export function DistributionPage() { return <PageFrame title="Hardware Distribution" description="Hardware and construction product supply for dealers, retailers, contractors and builders across Kerala."><h2 className="section-title">Products for Distribution</h2><DistributionLists /><div className="detail-grid">{distribution.map(d => <div className="detail-item" key={d.name}><h2>{d.name}</h2><p>{d.items.join(', ')}.</p></div>)}</div><div className="mt-10"><h2 className="section-title">Distribution Services</h2><ServiceList /><Button asChild variant="gold"><Link to="/contact">Partner With Us <ArrowRight /></Link></Button></div></PageFrame> }
export function BrandsPage() { return <PageFrame title="Our Brands" description="Trusted names in building materials, electrical, plumbing and home solutions."><h2 className="section-title">Trusted Partner Brands</h2><TrustedBrands /><div className="mt-9"><Button asChild variant="gold"><Link to="/contact">Enquire About Brands <ArrowRight /></Link></Button></div></PageFrame> }
const serviceDescriptions = ['Supply for hardware dealers and their customer requirements.', 'Discuss project quantities and wholesale purchasing with our team.', 'Product selection and supply support for retail businesses.', 'Materials for contractors, builders and project requirements.', 'Speak with our team about product choices and purchasing enquiries.', 'Discuss delivery arrangements for your location and order.', 'Contact our team to confirm current stock before ordering.'];
export function ServicesPage() { return <PageFrame title="Our Services" description="Retail, wholesale and distribution support for homeowners, trade professionals and businesses."><div className="detail-grid">{services.map((s, i) => <div key={s} className="detail-item"><h2>{s}</h2><p>{serviceDescriptions[i]}</p></div>)}</div><div className="my-10"><WhyChoose /></div><Button asChild variant="gold"><Link to="/contact">Discuss Your Requirements <ArrowRight /></Link></Button></PageFrame> }
export function ContactPage() { const [interest, setInterest] = useState('Hardware'); return <PageFrame title="Contact Keerthi" description="Tell us what you need. Get in touch for retail purchases, wholesale orders or distribution enquiries."><div className="contact-page-grid"><section><h2>Keerthi Agencies</h2><div className="contact-line"><Phone /><div>{business.phones.map((p, i) => <p key={p}><a href={business.phoneLinks[i]} onClick={() => trackEvent('phone_click')}>{p}</a></p>)}</div></div><div className="contact-line"><Mail /><a href={`mailto:${business.email}`}>{business.email}</a></div><div className="contact-line"><MapPin /><address>{business.address}</address></div><p className="text-sm text-muted-foreground">GSTIN: {business.gstin}</p><div className="mt-6"><Button asChild variant="goldOutline"><a href="https://www.google.com/maps/search/?api=1&query=Athikkayam+Bus+Stand+Pathanamthitta+Kerala+689711" target="_blank" rel="noopener noreferrer"><MapPin />Get Directions</a></Button></div></section><section><h2>Send an Enquiry</h2><form className="enquiry-form" onSubmit={e => { e.preventDefault(); const data = new FormData(e.currentTarget); const name = String(data.get('name') ?? '').trim(); const phone = String(data.get('phone') ?? '').trim(); const message = String(data.get('message') ?? '').trim(); if (!name || !phone) return; trackEvent('enquiry_submit', { interest }); window.open(enquiryLink(name, phone, interest, message), '_blank', 'noopener,noreferrer') }}><div className="form-row"><label>Your Name<input name="name" required maxLength={100} autoComplete="name" placeholder="Full name" /></label><label>Phone Number<input name="phone" type="tel" required pattern="[+0-9 ()-]{7,20}" maxLength={20} autoComplete="tel" placeholder="Your phone number" /></label></div><label>Interested In<select value={interest} onChange={e => setInterest(e.target.value)}>{categories.map(c => <option key={c.slug}>{c.name}</option>)}<option>Wholesale / Distribution</option><option>Other Enquiry</option></select></label><label>Your Requirements<textarea name="message" maxLength={2000} placeholder="Products, quantities or project details" required /></label><p className="form-note">Your enquiry will open in WhatsApp. Review your message there and press send.</p><Button type="submit" variant="gold" size="lg"><MessageCircle />Continue on WhatsApp <ArrowRight /></Button></form></section></div></PageFrame> }
